{ config, pkgs, lib, ... }:

{

services.hypridle = {
  enable = true;
  settings = {
      general = {
        #after_sleep_cmd = "hyprctl dispatch dpms on";
        ignore_dbus_inhibit = false;
        #lock_cmd = "";
      };
      listener = [
        {
          timeout = 600;
          on-timeout = "";
        }
        #{
        #  timeout = 900;
        #  on-timeout = "hyprctl dispatch dpms off";
        #  on-resume = "hyprctl dispatch dpms on";
        #}
      ];
  };
};

programs.hyprlock = {
	enable = true;
	settings = {
	  	general = {
      			hide_cursor = true;
      			ignore_empty_input = true;
   	 	};

    		#animations = {
      		#	enabled = false;
      		#	fade_in = {
        	#		duration = 300;
        	#		bezier = "easeOutQuint";
      		#	};
      		#	fade_out = {
        	#		duration = 300;
        	#		bezier = "easeOutQuint";
      		#	};
    		#};
    		background = [
      		{
        		#path = "screenshot";
        		color = "rgba(20, 20, 20, 0.58)";
        		blur_passes = 1;
        		blur_size = 9;
      		}
    		];

    input-field = [
      {
        size = "400, 100";
        position = "0, 0";
        monitor = "";
        dots_center = true;
        fade_on_empty = false;
        font_color = "rgba(224, 222, 244, 1)";
        inner_color = "rgb(26, 25, 24)";
        outer_color = "rgb(188, 103, 47)";
        outline_thickness = 5;
        placeholder_text = "NixOS bloqueado...";
        shadow_passes = 1;
        check_color = "rgba(204, 136, 34, 1)";
        fail_color = "rgba(172, 67, 35, 1)";

        hide_input = false;
        hide_input_base_color = "rgba(240, 240, 240, 0.47)";
      }
    ];
	};

};

services.hyprpaper = {
	enable = true;
	settings = {
		preload = [""];
		wallpaper = [","];
	};
};


wayland.windowManager.hyprland = {
  enable = true;
  systemd.variables = ["--all"];
  settings = {

    ########################################################################################
    #AUTOGENERATED HYPR CONFIG.
    #PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
    #OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
    ########################################################################################

    #
    # Please note not all available settings / options are set here.
    # For a full list, see the wiki
    #

    # autogenerated = 1;  # remove this line to remove the warning

    # See https://wiki.hyprland.org/Configuring/Monitors/
    monitor = [
      "eDP-1,     1920x1080@144, 0x0,     1"
      "HDMI-A-1,  1920x1080@144, -1920x0, 1"
      "DP-2,	  1920x1080@60, -1920x1080, 1"
      "DP-1,	  1920x1080@144, -1920x0, 1"
      #"        ,  preferred    , -1920x0, 1"
      #",preferred,auto,1, mirror, eDP-1"
    ];

    # Variables de entorno env
    env = [
      "WLR_NO_HARDWARE_CURSORS,1"
      #"XCURSOR_SIZE,24"
      #"XCURSOR_THEME,Bibata-Modern-Ice"
      #"QT_QPA_PLATFORMTHEME,qt5ct"
      "XDG_CURRENT_DESKTOP,Hyprland"
      "GTK_THEME,Adwaita:dark"
      "QT_STYLE_OVERRIDE,Fusion"
      "QT_QPA_PLATFORM,wayland"

      # Estos de abajo son sólo para cuando
      # tengas GPU Nvidia
      #"LIBVA_DRIVER_NAME,nvidia"
      #"__GLX_VENDOR_LIBRARY_NAME,nvidia"
    ];


    # Execute your favorite apps at launch
    exec-once = [
        "waybar &"
        "sleep 1 && dunst &"
        "sleep 2 && thunderbird &"
        "sleep 3 && obsidian &"
        "sleep 4 && spotify &"
	"DRI_PRIME=1 glxgears"
        #"systemctl --user enable opentabletdriver.service --now"
	#"nohup DRI_PRIME=1 glxgears > /dev/null 2>&1 &"
        #"/home/nekonix/configNix/scripts/refresco.sh"
        "systemctl --user start hyprpolkitagent"

        "/home/nekonix/configNix/scripts/alertaBateria.sh"
        "/home/nekonix/configNix/scripts/estadoBateria.sh"
        "/home/nekonix/configNix/scripts/temperaturaCpu.sh"
        #"sudo /home/nekonix/configNix/scripts/ventiladores.sh"
        #"/home/nekonix/descargar.sh"
        #"/nix/store/$(ls -la /nix/store | grep polkit-kde-agent | grep '^d' | awk '{print $9}' | head -n 1)/libexec/polkit-kde-authentication-agent-1"
      ];

      workspace = [
        "special:spotify, on-created-empty: spotify"
        "special:obsidian, on-created-empty: obsidian"
        "special:mail, on-created-empty: thunderbird"
        "1, monitor:DP-1, default:true, on-created-empty: firefox"
        "11, monitor:eDP-1, default:true, on-created-empty: /home/nekonix/configNix/scripts/adornosTerminal.sh"
      ];

      "$terminal" = "kitty";
      "$fileManager" = "thunar";
      "$menu" = "rofi -show drun -show-icons";
      # See https://wiki.hyprland.org/Configuring/Keywords/ for more
      "$mainMod" = "SUPER";


      # For all categories, see https://wiki.hyprland.org/Configuring/Variables/
      input = {
        kb_layout = "latam";
        numlock_by_default = true;
        follow_mouse = 1;

        touchpad = {
          natural_scroll = "yes";
          scroll_factor = 0.25;
        };

        sensitivity = -0.5;
      };

      general = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 2;
        gaps_out = 2;
        border_size = 1;
        "col.active_border" = "rgba(ec9255ee) rgba(ffb380ee) 45deg";
        "col.inactive_border" = "rgba(595959aa)";
        layout = "dwindle";

        # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false;
      };

      decoration = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 10;
        blur = {
          enabled = false;
          size = 3;
          passes = 1;
        };
        drop_shadow = "yes";
        shadow_range = 4;
        shadow_render_power = 3;
        "col.shadow" = "rgba(1a1a1aee)";
      };

      animations = {
        enabled = "yes";
        # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default"
        ];
      };

      dwindle = {
        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        pseudotile = "yes";
        preserve_split = "yes";
      };

      master = {
        # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_is_master = true;
      };

      cursor = {
        no_warps = false;
        warp_on_change_workspace = 0;
      };

      gestures = {
        # See https://wiki.hyprland.org/Configuring/Variables/ for more
        workspace_swipe = true;
        workspace_swipe_fingers = 3;
      };

      misc = {
        force_default_wallpaper = "";
        disable_hyprland_logo = true;
	session_lock_xray = true;
      };

      # Example per-device config
      # See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
      #"device:epic-mouse-v1" = {
      #  sensitivity = -0.5;
      #};



      # Example windowrule v1
      # windowrule = float, ^(kitty)$
      # Example windowrule v2
      # windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
      # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
      #windowrulev2 = ["nomaximizerequest, class:.*"];
      windowrulev2 = [
      		"workspace special:spotify silent, class:^(Spotify)$"
		"workspace special:obsidian silent, class:^(obsidian)$"
		"workspace special:mail silent, class:^(thunderbird)$"
		"workspace special:discord silent, class:^(vesktop)$"
		#"workspace 12 silent, title:^(glxgears)$"
		"opacity 0.1, size 20 20, move 1920 1080, pin, title:^(glxgears)$"
		#"opacity 0.5, no_initial_focus:on, no_anim: on, render_unfocused: on, class:^(krita)$"
		#"no_anim, class:^(krita)$"
	];


      # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
      bind = [
        "$mainMod, Q, exec, $terminal"
        "$mainMod, W, killactive,"
        "$mainMod, M, exit,"
        "$mainMod, E, exec, $fileManager"
        "$mainMod, R, exec, $menu"
        "$mainMod, P, exec, ~/configNix/scripts/mostrarFondo.sh"
        "$mainMod, S, togglesplit"
        "$mainMod, L, exec, ~/configNix/scripts/bloqueoPantalla.sh"
        "$mainMod, O, exec, ~/configNix/scripts/menuRofi.sh"
	
        "$mainMod, F, fullscreen"
        "$mainMod, period, exec, ~/configNix/scripts/emojis.sh"

        # Cambiar la ventana con focus
        "$mainMod, left, movefocus, l"
        #"$mainMod, J, movefocus, l"
        "$mainMod, right, movefocus, r"
        #"$mainMod, L, movefocus, r"
        "$mainMod, up, movefocus, u"
        #"$mainMod, I, movefocus, u"
        "$mainMod, down, movefocus, d"
        #"$mainMod, K, movefocus, d"

        # Ir al workspace selecionado
        "$mainMod, 1, workspace, 1"
        "$mainMod, 2, workspace, 2"
        "$mainMod, 3, workspace, 3"
        "$mainMod, 4, workspace, 4"
        "$mainMod, 5, workspace, 5"
        "$mainMod, 6, workspace, 6"
        "$mainMod, 7, workspace, 7"
        "$mainMod, 8, workspace, 8"
        "$mainMod, 9, workspace, 9"
        "$mainMod, 0, workspace, 10"

        "$mainMod, F1, workspace, 11"
        "$mainMod, F2, workspace, 12"
        "$mainMod, F3, workspace, 13"
        "$mainMod, F4, workspace, 14"
        "$mainMod, F5, workspace, 15"
        "$mainMod, F6, workspace, 16"
        "$mainMod, F7, workspace, 17"
        "$mainMod, F8, workspace, 18"
        "$mainMod, F9, workspace, 19"
        "$mainMod, F10, workspace, 20"

        # Mover la ventana con focus al workspace seleccionado
        "$mainMod SHIFT, 1, movetoworkspace, 1"
        "$mainMod SHIFT, 2, movetoworkspace, 2"
        "$mainMod SHIFT, 3, movetoworkspace, 3"
        "$mainMod SHIFT, 4, movetoworkspace, 4"
        "$mainMod SHIFT, 5, movetoworkspace, 5"
        "$mainMod SHIFT, 6, movetoworkspace, 6"
        "$mainMod SHIFT, 7, movetoworkspace, 7"
        "$mainMod SHIFT, 8, movetoworkspace, 8"
        "$mainMod SHIFT, 9, movetoworkspace, 9"
        "$mainMod SHIFT, 0, movetoworkspace, 10"

        "$mainMod SHIFT, F1, movetoworkspace, 11"
        "$mainMod SHIFT, F2, movetoworkspace, 12"
        "$mainMod SHIFT, F3, movetoworkspace, 13"
        "$mainMod SHIFT, F4, movetoworkspace, 14"
        "$mainMod SHIFT, F5, movetoworkspace, 15"
        "$mainMod SHIFT, F6, movetoworkspace, 16"
        "$mainMod SHIFT, F7, movetoworkspace, 17"
        "$mainMod SHIFT, F8, movetoworkspace, 18"
        "$mainMod SHIFT, F9, movetoworkspace, 19"
        "$mainMod SHIFT, F10, movetoworkspace, 20"

        # Workspaces especiales
        "$mainMod, Z, togglespecialworkspace, spotify"
        "$mainMod SHIFT, Z, movetoworkspace, special:spotify"
        "$mainMod, X, togglespecialworkspace, obsidian"
        "$mainMod SHIFT, X, movetoworkspace, special:obsidian"
        "$mainMod, C, togglespecialworkspace, mail"
        "$mainMod SHIFT, C, movetoworkspace, special:mail"


        # Moverse entre workspaces. Rueda ratón y con teclas A, D
        "$mainMod, mouse_down, workspace, e-1"
        "$mainMod, mouse_up, workspace, e+1"
        "$mainMod, A, workspace, e-1"
        ",mouse:275, workspace, e+1"
        ",mouse:276, workspace, e-1"
        "$mainMod, D, workspace, e+1"
        
        # Control de media
        ", XF86AudioPlay, exec, playerctl play-pause"
        ", XF86AudioNext, exec, playerctl next"
        ", XF86AudioPrev, exec, playerctl previous"
        ", XF86AudioStop, exec, playerctl stop"

        # Pantallazos
        ", Print, exec, grim -g \"$(slurp -d)\" - | tee \"$HOME/Pictures/$(date +%Y%m%d_%H%M%S)_grim.png\" | wl-copy"
        #", Print, exec, grim -g \"$(slurp -d)\" - | wl-copy"
      ];

      # Los bindm son cuando se usan los botones del mouse
      # mouse:272 es click izquierdo
      # mouse:273 es click derecho
      bindm = [
        "$mainMod, mouse:272, movewindow"
        "$mainMod, mouse:273, resizewindow"
      ];


      # Los binde son cuando puedes dejar presionada la tecla
      # y seguirá ejecutando el comando
      binde = [
        # Controles de volumen
        #", XF86audioraisevolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1% && dunstify -r 91190 -u low \"Volumen +\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')\""
        #", XF86audiolowervolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1% && dunstify -r 91190 -u low \"Volumen -\" \"$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')\""
        #", XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle && dunstify -r 91190 -u low \"Silenciado\" \"$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')\""
        

        ", XF86AudioRaiseVolume, exec, ~/configNix/scripts/volumen.sh up"
        ", XF86AudioLowerVolume, exec, ~/configNix/scripts/volumen.sh down"
        ", XF86AudioMute, exec, ~/configNix/scripts/volumen.sh mute"

        # MUTE
        #", XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle && MUTE=\$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print \$2}') && MSG=\$( [ \"\$MUTE\" = \"yes\" ] && echo \"🔇 Silenciado\" || echo \"🔊 Activado\") && dunstify -r 91190 -u low \"Mute\" \"\$MSG\""



        # Controles de brillo
        ", XF86MonBrightnessUp, exec, brightnessctl set 5%+"
        ", XF86MonBrightnessDown, exec, brightnessctl set 5%-"
      ];

      debug = {
        suppress_errors = true;
      };







  };

};









}
